Training.Web/Models/Good.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Training.Web.Models
{

    [Table("Goods")]
    public class Good
    {
        [Key]
        public int Id { get; set; }

        [Required, Display(Name = "Назва"), MaxLength(50)]
        public string Name { get; set; }

        [Required, Display(Name = "Статус")]
        public GoodsStatus Status { get; set; }

        [Display(Name = "Опис"), MaxLength(100)]
        public string Description { get; set; }

        [Display(Name = "Оціночна вартість")]
        public decimal AppraisedValue { get; set; }

        [ValidateNever]
        public int CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [ValidateNever]
        [Display(Name = "Категорія товару")]
        public Category Category { get; set; }

    }
}

Training.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Training.Web.Data;
using Training.Web.Models;

namespace Training.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDBContext _db;

        public CategoryController(ApplicationDBContext db)
        {
            _db = db;
        }

        //GET
        [HttpGet, ActionName("Upsert")]
        public async Task<IActionResult> UpsertGetAsync(int? id)
        {
            Category category = new();

            if (id == null || id == 0)
            {
                return View(category);
            }
            else
            {
                category = await _db.Categories.FirstOrDefaultAsync(u => u.Id == id);
                return View(category);
            }
        }

        [HttpPost, ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpsertPostAsync(Category obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    await _db.Categories.AddAsync(obj);
                }
                else
                {
                    _db.Categories.Update(obj);
                }

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), nameof(Good));
            }

            return View(obj);
        }

        //GET
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> DeleteGetAsync(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = await _db.Categories.FirstOrDefaultAsync(u => u.Id == id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {
         
            var category = await _db.Categories.FirstOrDefaultAsync(u => u.Id == id);
            bool isGoodsWithSelectedCategoryExists = _db.Goods.Any(i => i.CategoryId == id);
            if(isGoodsWithSelectedCategoryExists)
            {
                TempData["error"] = "Не можна видалити Категорію , бо існують товари з заданою категорією";
                return RedirectToAction(nameof(Index), nameof(Good));
            }

            if (category == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(category);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), nameof(Good));
        }
    }
}

Training.Web/Controllers/GoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Training.Web.Data;
using Training.Web.Models;
using Training.Web.Services;
using static iTextSharp.text.pdf.AcroFields;

namespace Training.Web.Controllers
{
    public class GoodController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly IGoodsService _goodsService;
        public GoodController(ApplicationDBContext db, IGoodsService goodsService)
        {
            _db = db;
            _goodsService = goodsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? status)
        {
            IEnumerable<Category> objCategoryList = await _db.Categories.ToListAsync();
            IEnumerable<RegisteredInvoice> registeredInvoices = await _db.RegisteredInvoices.Include(x => x.Good).ToListAsync();
            IEnumerable<Good> objGoodList = registeredInvoices.Select(x => x.Good).ToList();
            foreach (var item in registeredInvoices) 
            {
                _goodsService.CheckStorageExpirationDate(item);
            }

            var objGoodsTableModel = objGoodList.Select(p => 
                new GoodsTableModel {
                    Id = p.Id,
                    Name = p.Name,
                    Description = p.Description,
                    Status = p.Status,
                    AppraisedValue = p.AppraisedValue,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    Commision = Math.Round((p.AppraisedValue * p.Category.Commision) / 100, 2)}
            ).ToList();


            if (String.IsNullOrEmpty(status) || status == "-1")
            {
                    objGoodsTableModel = objGoodList.Select(p =>
                    new GoodsTableModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Description = p.Description,
                        Status = p.Status,
                        AppraisedValue = p.AppraisedValue,
                        Category = p.Category,
                        CategoryId = p.CategoryId,
                        Commision = Math.Round((p.AppraisedValue * p.Category.Commision) / 100, 2)
                    }
                ).ToList();
            }
            else
            {
                objGoodsTableModel = objGoodsTableModel.Where(x => x.Status.ToString() == status).ToList();
            }

            SelectList StatusGoodsList = new SelectList(
                    new List<SelectListItem>
                    {
                        new SelectListItem { Text = $"Всі", Value = "-1"},
                        new SelectListItem { Text = $"{GoodsStatusString.STORING}", Value = GoodsStatus.Storing.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.EXPIRED}", Value = GoodsStatus.Expired.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.ONSALE}", Value = GoodsStatus.OnSale.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.SOLD}", Value = GoodsStatus.Sold.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.RETURNED}", Value =  GoodsStatus.Returned.ToString()},
                    }, "Value", "Text");

            var model = new GeneralModel { CategoryList = objCategoryList, GoodList = objGoodsTableModel , StatusGoodsList = StatusGoodsList };
            return View(model);
        }

        [HttpGet, ActionName("PutOnSale")]
        public async Task<IActionResult> PutUpForSale(int? id) 
        {
            var goods = _db.Goods.FirstOrDefaultAsync(x => x.Id == id).Result;
            _goodsService.PutUpOnSale(goods);
            _db.Update(goods);

            await _db.SaveChangesAsync();
            return RedirectToAction("Index", nameof(Good));
        }

        [HttpGet, ActionName("Return")]
        public async Task<IActionResult> Return(int? id)
        {
            var goods = _db.Goods.FirstOrDefaultAsync(x => x.Id == id).Result;
            _goodsService.Return(goods);
            _db.Update(goods);

            await _db.SaveChangesAsync();
            return RedirectToAction("Index", nameof(Good));
        }

        [HttpGet, ActionName("Upsert")]
        public async Task<IActionResult> UpsertGetAsync(int? id)
        {
           
            Good good = new();
            ViewBag.Categories = await _db.Categories.ToListAsync();
            if (id == null || id == 0)
            {
                return View(good);
            }
            else
            {
                good = await _db.Goods.FirstOrDefaultAsync(u => u.Id == id);
                return View(good);
            } 
        }

        [HttpPost, ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpsertPostAsync(Good obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id != 0)
                {
                    _db.Goods.Update(obj);
                    await _db.SaveChangesAsync();
                }
                var serializedObj = JsonConvert.SerializeObject(obj);
                TempData["currentGoods"] = serializedObj;
                return RedirectToAction("Add", nameof(RegisteredInvoice));
            }

            return View(obj);
        }

        //GET
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> DeleteGetAsync(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var good = await _db.Goods.Include(p => p.Category).FirstOrDefaultAsync(u => u.Id == id);

            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {
            var good = await _db.Goods.FirstOrDefaultAsync(u => u.Id == id);
            
            if (good == null)
            {
                return NotFound();
            }
            _db.Goods.Remove(good);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




    }
}

Training.Web/Controllers/RegisteredInvoiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Training.Web.Data;
using Training.Web.Models;

namespace Training.Web.Controllers
{
    public class RegisteredInvoiceController : Controller
    {
        private readonly ApplicationDBContext _db;

        public RegisteredInvoiceController(ApplicationDBContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? Id)
        {
            var data = _db.RegisteredInvoices
                .Include(x => x.Good)
                .Include(x => x.Client)
                .ToList().Where(x => Id == null ||  x.Good.Id == Id);

            return View(data);
        }


        [HttpGet, ActionName("Add")]
        public async Task<IActionResult> AddGetAsync()
        {
            RegisteredInvoice invoice = new();
            Good goods = JsonConvert.DeserializeObject<Good>(TempData["currentGoods"] as string);
            invoice.Good = goods;
            invoice.GoodId = goods.Id;
            ViewBag.Clients = await _db.Clients.ToListAsync();
            return View(invoice);

        }

        [HttpPost, ActionName("Add")]
        public async Task<IActionResult> AddPostAsync(RegisteredInvoice invoice) 
        {
            if (ModelState.IsValid) 
            {
                invoice.Client = await _db.Clients.FirstOrDefaultAsync(x => x.Id == invoice.ClientId);
                var goodsJson = Request.Form["goodsClass"].ToString();
                invoice.Good = JsonConvert.DeserializeObject<Good>(goodsJson);
                _db.Goods.Add(invoice.Good);
                _db.RegisteredInvoices.Add(invoice);
                await _db.SaveChangesAsync();
                TempData["success"] = "Товар та Імену накладну успішно сформовано!";
                return RedirectToAction(nameof(Index), nameof(RegisteredInvoice));
            }
            return View();
        }
    }
}

Training.Web/Controllers/SalesInvoiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Training.Web.Data;
using Training.Web.Models;
using Training.Web.Services;

namespace Training.Web.Controllers
{
    public class SalesInvoiceController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly IGoodsService _goodsService;

        public SalesInvoiceController(ApplicationDBContext db, IGoodsService goodsService)
        {
            _db = db;
            _goodsService = goodsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<SalesInvoice> objSalesInvoiceList = await _db.SalesInvoices.
                                                                   Include(x=>x.Sell).
                                                                   Include(x => x.Sell.Good).
                                                                   ToListAsync();
            return View(objSalesInvoiceList);
        }

        [HttpGet, ActionName("Add")]
        public async Task<IActionResult> AddGetAsync(int? id)
        {
            SalesInvoice invoice = new();

            Sell sell = new();
            var goods = await _db.Goods.Include(x => x.Category).FirstOrDefaultAsync(x => x.Id == id);

            sell.Price = (goods.AppraisedValue + Math.Round((goods.AppraisedValue * goods.Category.Commision) / 100, 2));
            sell.Good = goods;
            invoice.Sell = sell;

            return View(invoice);
        }

        [HttpPost, ActionName("Add")]
        public async Task<IActionResult> AddPostAsync(SalesInvoice invoice)
        {
            if (ModelState.IsValid)
            {
                var sellJson = Request.Form["sellClass"].ToString();
                invoice.Sell = JsonConvert.DeserializeObject<Sell>(sellJson);
                var goods = invoice.Sell.Good;
                _goodsService.Sell(goods);
                _db.Update(goods);
                _db.Add(invoice.Sell);
                _db.Add(invoice);
                await _db.SaveChangesAsync();

                TempData["success"] = "Видаткову накладну успішно сформовано!";
                return RedirectToAction(nameof(Index), nameof(SalesInvoice));
            }
            return View();
        }
    }
}

Training.Web/Views/Good/Index.cshtml
@model GeneralModel

@{
    ViewData["Title"] = "Товари";
}

<partial name="_Notification" />
<br />
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                Категорії товарів
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
            <div class="accordion-body">
                <div class="row pt-4">
                    <div class="col-12 text-end">
                        <a asp-controller="Category" asp-action="Upsert" class="btn btn-primary">
                            <i class="bi bi-clipboard2-plus"></i> &nbsp; Створити категорію
                        </a>
                    </div>
                </div>
                <br />
                <table class="table table-bordered table-striped" style="width:50%;margin:auto">
                    <thead>
                        <tr class="table-primary">
                            <th>Назва </th>
                            <th>Комісійні, %</th>
                            <th></th>
                    </thead>
                    <tbody>
                        @foreach (var obj in Model.CategoryList)
                        {
                            <tr>
                                <td width="30%">@obj.Name</td>
                                <td width="10%">@obj.Commision</td>
                                <td width="10%">
                                    <div class="btn-qroup text-center" role="group">
                                        <a asp-controller="Category" asp-action="Upsert" asp-route-id="@obj.Id"><i class="bi bi-pencil"></i></a>
                                        &nbsp;
                                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id"><i class="bi bi-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12 text-end">
            <a asp-controller="Good" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-clipboard2-plus"></i> &nbsp; Додати товар
            </a>
        </div>
    </div>
    <br />
    <form method="get">
        <div style="display: flex; justify-content: center; align-items: center;">
            <select name="status" style="width:50%" asp-items="@Model.StatusGoodsList" class="form-select" >
                    <option value="">--Оберіть фільтр--</option>
             </select>
            &nbsp;&nbsp;&nbsp;
            <input type="submit" value="Фільтрувати" class="btn btn-outline-success" />
        </div>
    </form>
    <br />
    <table class="table table-bordered table-striped" style="width:100%;">
        <thead>
            <tr class="table-primary">
                <th>Назва</th>
                <th>Статус</th>
                <th>Опис</th>
                <th>Оціночна Вартість, грн</th>
                <th>Категорія</th>
                <th>Розраховані комісійні, грн</th>
                <th></th>
                <th></th>
        </thead>
        <tbody>
            @foreach (var obj in Model.GoodList)
            {
                <tr>
                    <td>@obj.Name</td>
                    <td>@obj.Status</td>
                    <td>@obj.Description</td>
                    <td>@obj.AppraisedValue</td>
                    <td>@obj.Category.Name</td>
                    <td>@obj.Commision</td>
                    
                    <td width="10%">
                        <div class="btn-qroup text-center" role="group">
                            <a asp-controller="Good" asp-action="Upsert" asp-route-id="@obj.Id"><i class="bi bi-pencil"></i></a>
                            &nbsp;
                            <a asp-controller="Good" asp-action="Delete" asp-route-id="@obj.Id"><i class="bi bi-trash"></i></a>
                            &nbsp;
                            <a asp-controller="RegisteredInvoice" asp-action="Index" asp-route-id="@obj.Id"><i class="bi bi-arrow-down-left-square-fill"></i></a>
                            
                        </div>
                    </td>

                    <td width="10%">
                        <div class="btn-qroup text-center" role="group">
                            @if (((int)obj.Status) == 0)
                            {
                                <a class="btn btn-success" asp-controller="Good" asp-action="Return" asp-route-id="@obj.Id">Повернути</a>
                            }
                            @if(((int)obj.Status) == 1)
                            {
                                <a class="btn btn-primary" asp-controller="Good" asp-action="PutOnSale" asp-route-id="@obj.Id">Виставити на продаж</a>
                            }
                            @if(((int)obj.Status) == 2)
                            {
                                <a class="btn btn-danger" method="get" asp-controller="SalesInvoice" asp-action="Add" asp-route-id="@obj.Id">Продати</a>
                            }
                        </div>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>