Training.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Training.Web.Data;
using Training.Web.Models;

namespace Training.Web.Controllers
{
    public class ClientController : Controller
    {
        private readonly ApplicationDBContext _db;

        public ClientController(ApplicationDBContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Client> objClientList = await _db.Clients.ToListAsync();
            return View(objClientList);
        }

        //GET
        [HttpGet, ActionName("Upsert")]
        public async Task<IActionResult> UpsertGetAsync(int? id)
        {
            Client client = new();

            if(id ==null || id == 0)
            {
                return View(client);
            }
            else
            {
                client = await _db.Clients.FirstOrDefaultAsync(u => u.Id == id);
                return View(client);
            }
        }

        [HttpPost, ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpsertPostAsync(Client obj)
        {
            
            if(ModelState.IsValid)
            {
                if(obj.Id == 0)
                {
                    await _db.Clients.AddAsync(obj);
                }
                else
                {
                    _db.Clients.Update(obj);
                }

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(obj);
        }

        //GET
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> DeleteGetAsync(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var client = await _db.Clients.FirstOrDefaultAsync(u => u.Id == id);

            if(client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {
           var client = await _db.Clients.FirstOrDefaultAsync(u => u.Id == id);

           if(client == null)
           {
               return NotFound();
           }
            _db.Clients.Remove(client);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Training.Web/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using Training.Web.Data;
using Training.Web.Services;

namespace Training.Web.Controllers
{
    public class FileController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IDocumentGenerationService _docGenService;
        public FileController(IWebHostEnvironment env, IDocumentGenerationService docGenService)
        {
            _env = env;
            _docGenService = docGenService;
        }

        [HttpGet, ActionName("Download")]
        public ActionResult Download()
        {
            var contentFolder = Path.Combine(_env.ContentRootPath, "Content");
            string fileName = "Report.pdf";
            var filePath = Path.Combine(contentFolder, fileName);

            _docGenService.GenerateDocument(contentFolder, fileName);

            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

Training.Web/Controllers/GoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Training.Web.Data;
using Training.Web.Models;
using Training.Web.Services;
using static iTextSharp.text.pdf.AcroFields;

namespace Training.Web.Controllers
{
    public class GoodController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly IGoodsService _goodsService;
        public GoodController(ApplicationDBContext db, IGoodsService goodsService)
        {
            _db = db;
            _goodsService = goodsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? status)
        {
            IEnumerable<Category> objCategoryList = await _db.Categories.ToListAsync();
            IEnumerable<RegisteredInvoice> registeredInvoices = await _db.RegisteredInvoices.Include(x => x.Good).ToListAsync();
            IEnumerable<Good> objGoodList = registeredInvoices.Select(x => x.Good).ToList();
            foreach (var item in registeredInvoices) 
            {
                _goodsService.CheckStorageExpirationDate(item);
            }

            var objGoodsTableModel = objGoodList.Select(p => 
                new GoodsTableModel {
                    Id = p.Id,
                    Name = p.Name,
                    Description = p.Description,
                    Status = p.Status,
                    AppraisedValue = p.AppraisedValue,
                    Category = p.Category,
                    CategoryId = p.CategoryId,
                    Commision = Math.Round((p.AppraisedValue * p.Category.Commision) / 100, 2)}
            ).ToList();


            if (String.IsNullOrEmpty(status) || status == "-1")
            {
                    objGoodsTableModel = objGoodList.Select(p =>
                    new GoodsTableModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Description = p.Description,
                        Status = p.Status,
                        AppraisedValue = p.AppraisedValue,
                        Category = p.Category,
                        CategoryId = p.CategoryId,
                        Commision = Math.Round((p.AppraisedValue * p.Category.Commision) / 100, 2)
                    }
                ).ToList();
            }
            else
            {
                objGoodsTableModel = objGoodsTableModel.Where(x => x.Status.ToString() == status).ToList();
            }

            SelectList StatusGoodsList = new SelectList(
                    new List<SelectListItem>
                    {
                        new SelectListItem { Text = $"Всі", Value = "-1"},
                        new SelectListItem { Text = $"{GoodsStatusString.STORING}", Value = GoodsStatus.Storing.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.EXPIRED}", Value = GoodsStatus.Expired.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.ONSALE}", Value = GoodsStatus.OnSale.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.SOLD}", Value = GoodsStatus.Sold.ToString()},
                        new SelectListItem { Text = $"{GoodsStatusString.RETURNED}", Value =  GoodsStatus.Returned.ToString()},
                    }, "Value", "Text");

            var model = new GeneralModel { CategoryList = objCategoryList, GoodList = objGoodsTableModel , StatusGoodsList = StatusGoodsList };
            return View(model);
        }

        [HttpGet, ActionName("PutOnSale")]
        public async Task<IActionResult> PutUpForSale(int? id) 
        {
            var goods = _db.Goods.FirstOrDefaultAsync(x => x.Id == id).Result;
            _goodsService.PutUpOnSale(goods);
            _db.Update(goods);

            await _db.SaveChangesAsync();
            return RedirectToAction("Index", nameof(Good));
        }

        [HttpGet, ActionName("Return")]
        public async Task<IActionResult> Return(int? id)
        {
            var goods = _db.Goods.FirstOrDefaultAsync(x => x.Id == id).Result;
            _goodsService.Return(goods);
            _db.Update(goods);

            await _db.SaveChangesAsync();
            return RedirectToAction("Index", nameof(Good));
        }

        [HttpGet, ActionName("Upsert")]
        public async Task<IActionResult> UpsertGetAsync(int? id)
        {
           
            Good good = new();
            ViewBag.Categories = await _db.Categories.ToListAsync();
            if (id == null || id == 0)
            {
                return View(good);
            }
            else
            {
                good = await _db.Goods.FirstOrDefaultAsync(u => u.Id == id);
                return View(good);
            } 
        }

        [HttpPost, ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpsertPostAsync(Good obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id != 0)
                {
                    _db.Goods.Update(obj);
                    await _db.SaveChangesAsync();
                }
                var serializedObj = JsonConvert.SerializeObject(obj);
                TempData["currentGoods"] = serializedObj;
                return RedirectToAction("Add", nameof(RegisteredInvoice));
            }

            return View(obj);
        }

        //GET
        [HttpGet, ActionName("Delete")]
        public async Task<IActionResult> DeleteGetAsync(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var good = await _db.Goods.Include(p => p.Category).FirstOrDefaultAsync(u => u.Id == id);

            if (good == null)
            {
                return NotFound();
            }

            return View(good);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {
            var good = await _db.Goods.FirstOrDefaultAsync(u => u.Id == id);
            
            if (good == null)
            {
                return NotFound();
            }
            _db.Goods.Remove(good);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




    }
}

Training.Web/Controllers/SalesInvoiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Training.Web.Data;
using Training.Web.Models;
using Training.Web.Services;

namespace Training.Web.Controllers
{
    public class SalesInvoiceController : Controller
    {
        private readonly ApplicationDBContext _db;
        private readonly IGoodsService _goodsService;

        public SalesInvoiceController(ApplicationDBContext db, IGoodsService goodsService)
        {
            _db = db;
            _goodsService = goodsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<SalesInvoice> objSalesInvoiceList = await _db.SalesInvoices.
                                                                   Include(x=>x.Sell).
                                                                   Include(x => x.Sell.Good).
                                                                   ToListAsync();
            return View(objSalesInvoiceList);
        }

        [HttpGet, ActionName("Add")]
        public async Task<IActionResult> AddGetAsync(int? id)
        {
            SalesInvoice invoice = new();

            Sell sell = new();
            var goods = await _db.Goods.Include(x => x.Category).FirstOrDefaultAsync(x => x.Id == id);

            sell.Price = (goods.AppraisedValue + Math.Round((goods.AppraisedValue * goods.Category.Commision) / 100, 2));
            sell.Good = goods;
            invoice.Sell = sell;

            return View(invoice);
        }

        [HttpPost, ActionName("Add")]
        public async Task<IActionResult> AddPostAsync(SalesInvoice invoice)
        {
            if (ModelState.IsValid)
            {
                var sellJson = Request.Form["sellClass"].ToString();
                invoice.Sell = JsonConvert.DeserializeObject<Sell>(sellJson);
                var goods = invoice.Sell.Good;
                _goodsService.Sell(goods);
                _db.Update(goods);
                _db.Add(invoice.Sell);
                _db.Add(invoice);
                await _db.SaveChangesAsync();

                TempData["success"] = "Видаткову накладну успішно сформовано!";
                return RedirectToAction(nameof(Index), nameof(SalesInvoice));
            }
            return View();
        }
    }
}

Training.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Ломбард Fourty Two</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ломбард</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Клієнти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Good" asp-action="Index">Товари</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegisteredInvoice" asp-action="Index">Ім. Накладні</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesInvoice" asp-action="Index">Вид. Накладні</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Download">Завантажити звіт</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fourty two
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   @* <script src="~/js/bootstrap.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Training.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}